---
- name: Deploy Istio Proxy to External VM
  hosts: istio_vms
  become: true
  vars:
    istio_proxy_rpm_url: "{{ lookup('env', 'ISTIO_PROXY_RPM_URL') }}"
    work_dir: "{{ playbook_dir }}/../curl-vm-config"

  tasks:
  - name: Configure the BaseOS repository providing istio-proxy dependencies
    ansible.builtin.yum_repository:
      name: baseos
      description: CentOS Stream 9 BaseOS
      baseurl: https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/
      gpgcheck: yes
      gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official
      enabled: yes
      state: present

  - name: Add Istio proxy repository
    ansible.builtin.yum_repository:
      name: istio-proxy
      description: Istio Proxy Repository
      baseurl: "{{ istio_proxy_rpm_url }}"
      gpgcheck: false
      sslverify: false

  - name: Install istio-proxy package
    ansible.builtin.package:
      name: istio-proxy.x86_64
      state: present

  # This is a workaround - the tokens directory should be managed by the RPM
  - name: Create required directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    loop:
    - /var/run/secrets/tokens

  - name: Deploy Root Certificate
    ansible.builtin.copy:
      src: "{{ work_dir }}/root-cert.pem"
      dest: /etc/certs/root-cert.pem
      mode: '0644'

  - name: Deploy Istio Token
    ansible.builtin.copy:
      src: "{{ work_dir }}/istio-token"
      dest: /var/run/secrets/tokens/istio-token
      mode: '0600'

  - name: Deploy cluster.env configuration
    ansible.builtin.copy:
      src: "{{ work_dir }}/cluster.env"
      dest: /var/lib/istio/envoy/cluster.env
      mode: '0644'

  - name: Deploy mesh.yaml configuration
    ansible.builtin.copy:
      src: "{{ work_dir }}/mesh.yaml"
      dest: /etc/istio/config/mesh
      mode: '0644'

  - name: Append generated hosts configuration to /etc/hosts
    ansible.builtin.blockinfile:
      path: /etc/hosts
      block: "{{ lookup('file', work_dir + '/hosts') }}"
      marker: "# {mark} ANSIBLE MANAGED ISTIO HOSTS"

  - name: Set ownership for Istio directories and files
    ansible.builtin.file:
      path: "{{ item }}"
      owner: istio-proxy
      recurse: true
    loop:
    - /var/run/secrets

  - name: Enable and start istio-proxy service
    ansible.builtin.systemd:
      name: istio-proxy
      state: started
      enabled: true
